services:
  workspace:
    image: mcr.microsoft.com/devcontainers/python:3.0.8-3.10-trixie
    volumes:
      - op:/home/vscode/.config/op
      - aws:/home/vscode/.aws
      - cache:/home/vscode/.cache:delegated
    environment:
      AWS_ENDPOINT_URL: ${AWS_ENDPOINT_URL:-}
    healthcheck:
      disable: true

  localstack:
    image: localstack/localstack:4@sha256:3ebc37595918b8accb852f8048fef2aff047d465167edd655528065b07bc364a
    profiles:
      - localstack
    ports:
      - ${LOCALSTACK_GATEWAY_HOST:-127.0.0.1}:${LOCALSTACK_GATEWAY_PORT:-4566}:4566
      - ${LOCALSTACK_EXTERNAL_SERVICES_HOST:-127.0.0.1}:${LOCALSTACK_EXTERNAL_SERVICES_PORT_RANGE:-4510-4559}:4510-4559
    volumes:
      - localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  op:
  aws:
  cache:
  localstack:
